spring:
  datasource:
    url: jdbc:mysql://117.50.18.49:3306/finance
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8888
